import Head from "next/head"
import Link from "next/link"
import { Navbar } from "../components/Navbar"
import styles from "./MainLayout.module.css";
import * as React from "react";

type Props = {
  children?: React.ReactNode
};

export const MainLayout: React.FC<Props> = ({children}) => {
  return (
    <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navbar/>
    <main className={styles.main}>
        {children}
    </main>
  </div>
  )
}
